### ISSUE TITLE
Backup migration

### ISSUE THREAD

**Issue by warudin** [ThemeFuse/Unyson-Documentation#18]
I noticed that the latest documentation about the Backup extension doesn't contain any information about migrating content to another location. 

This page contains some information, but it's not totally correct:
http://manual.unyson.io/en/1.x/extension/backup/index.html

It says the backup should be moved to the folder uploads/backup/, but this should be uploads/fw-backup/

On a sidenote: I used this migration option this morning and it was working pretty good! The only problem I was having that I needed to active the right theme and all plugins.

**Comment by GheorgheP** [comment]
Thank you for reporting this, I will make the changes.

**Comment by warudin** [comment]
Thanks!
