### ISSUE TITLE
[suggestion] Typography option improvemants

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-Documentation#5]
http://screencast.com/t/OCSCWcGAOt

You might want to add the info about components array here . 
http://manual.unyson.io/en/latest/options/built-in-option-types.html#typography

https://github.com/ThemeFuse/Unyson/issues/195#event-227970487

**Comment by valeriuzdrobau** [comment]
http://manual.unyson.io/en/latest/options/built-in-option-types.html#typography
