### ISSUE TITLE
Check Unyson Manual Docs

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-Documentation#7]
Check Unyson Manual Docs

**Comment by VictoriaTF** [comment]
http://joxi.ru/VrwppZ1skYlDmX (trebuie "the same") - http://manual.unyson.io/en/latest/options/containers.html#content

http://joxi.ru/brRddv7h6z0n21 (“Looks as in the below example”)- http://manual.unyson.io/en/latest/options/containers.html#content

http://joxi.ru/vAWVVjgIlQYq2W ("is)- http://manual.unyson.io/en/latest/extensions/cookbook.html#content

http://joxi.ru/Q2KjjvOsqEbEmj ("be")- http://manual.unyson.io/en/latest/extension/portfolio/index.html#content

http://joxi.ru/BA0aaVgiZXlyry ("be" trebuie omis) - http://manual.unyson.io/en/latest/extension/events/index.html#content


http://joxi.ru/EA4aaVEiMyw0rb ("a" trebuie omis)- http://manual.unyson.io/en/latest/extension/learning/index.html#content

http://joxi.ru/YmEqqvLIqxwDm6 (This extension groups in one place all the settings that need  to work with social networks)- http://manual.unyson.io/en/latest/extension/social/index.html#content

http://joxi.ru/KAgEEjQF7aXNml (trebuie de utilizat articolul "an") -http://manual.unyson.io/en/latest/extension/social/index.html#content
