### ISSUE TITLE
Theme settings position in admin panel

### ISSUE THREAD

**Issue by maryslen** [ThemeFuse/Unyson-Documentation#8]
Hi, is a possibility to move Theme Setting out from the Appearance(admin menu)? To move it to the 1st level options?

Thank you

**Comment by moldcraft** [comment]
Hello,
You can use [this action](https://github.com/ThemeFuse/Unyson/blob/216cb4b561e9117d972c393abccdcadc904d59a3/framework/core/components/backend.php#L478-L482).

**Comment by maryslen** [comment]
The theme doesn't see hooks file. What can be a problem?

**Comment by moldcraft** [comment]
Oh, sorry, the `framework-customizations/theme/hooks.php` does not exist anymore (I will update that link).

Try `{theme}/inc/hooks.php` https://github.com/ThemeFuse/Theme-Includes

**Comment by maryslen** [comment]
Thank you!
